#pragma once

// Kept in sync with the foundation project viewer; see its comments for the RFS1 framing.
static const char CAMERA_WEB_VIEWER_HTML[] = R"HTML(<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="esp32s3-vision-viewer" content="1"><title>ESP32-S3 Camera Viewer</title><style>
:root{color-scheme:dark;font:16px system-ui,sans-serif;background:#10151b;color:#e8eef5}body{max-width:900px;margin:24px auto;padding:0 16px}h1{font-size:1.5rem}button{padding:9px 14px;margin:4px;border:0;border-radius:6px;background:#2878d0;color:white;cursor:pointer}button.secondary{background:#495563}.status{padding:10px;background:#202a35;border-radius:6px;margin:12px 0;white-space:pre-line}.dot{color:#9aa7b4}.ok{color:#62d394}.bad{color:#ff8585}.viewer{width:min(100%,640px);aspect-ratio:4/3;background:#000;display:block;image-rendering:pixelated}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:8px;margin:12px 0}.stat{background:#202a35;padding:9px;border-radius:5px}.stat b{display:block;color:#8ebfff;font-size:.82rem}.note{color:#b8c5d2;font-size:.92rem}
</style></head><body><h1>ESP32-S3 Camera Viewer</h1>
<p class="note">请连接 ESP32-S3 自建 Wi-Fi：<b>esp32s3cam-xxxx</b>，密码 11223344。默认地址 192.168.4.1。该网络没有 Internet 属于正常现象。</p>
<div class="status">连接状态：<span id="status" class="dot">正在连接视频流……</span></div>
<button id="reconnect">重新连接</button><button id="mode" class="secondary">切换到 MJPEG 兼容模式</button>
<canvas id="canvas" class="viewer" width="320" height="240"></canvas><img id="mjpeg" class="viewer" hidden alt="ESP32 摄像头视频">
<div class="stats"><div class="stat"><b>Stream FPS</b><span id="fps">--</span></div><div class="stat"><b>Processing FPS</b><span id="pfps">--</span></div><div class="stat"><b>Processing Time</b><span id="ptime">--</span></div><div class="stat"><b>Frame Bytes</b><span id="bytes">--</span></div><div class="stat"><b>Free Heap</b><span id="heap">--</span></div><div class="stat"><b>Free PSRAM</b><span id="psram">--</span></div></div>
<p class="note" id="connectionInfo"></p><p class="note" id="metricsStatus">Metrics 正在读取……</p>
<p class="note" id="debug"></p>
<script>
(()=>{
const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false}),img=document.getElementById('mjpeg');
const statusEl=document.getElementById('status'),modeBtn=document.getElementById('mode'),debugEl=document.getElementById('debug'),connectionInfo=document.getElementById('connectionInfo'),metricsStatus=document.getElementById('metricsStatus');
const MAX_FRAME_PIXELS=320*240,MAX_WIDTH=320,MAX_HEIGHT=240;
let mode='raw',activeKind='',controller=null,reader=null,mjpegResolve=null,retryTimer=null,metricsTimer=null,metricsController=null,metricsInFlight=false,runId=0,activeDone=Promise.resolve(),disposed=false;
let buffer=new Uint8Array(4096),head=0,used=0,rgba=new Uint8ClampedArray(MAX_FRAME_PIXELS*4),imageData=new ImageData(rgba,320,240),rawPixels=new Uint8Array(MAX_FRAME_PIXELS),decoded=0,dropped=0,errors=0,consecutiveErrors=0,resyncing=false,lastSequence='--',resolution='320×240';
const debug=new URLSearchParams(location.search).get('debug')==='1';
function state(text,kind='dot'){statusEl.textContent=text;statusEl.className=kind}
function clearRetry(){if(retryTimer!==null){clearTimeout(retryTimer);retryTimer=null}}
function resetQueue(){head=0;used=0}
function stopActive(){if(controller){controller.abort();controller=null}if(reader){reader.cancel().catch(()=>{});reader=null}if(mjpegResolve){const finish=mjpegResolve;mjpegResolve=null;finish('stopped')}img.onload=null;img.onerror=null;img.removeAttribute('src');resetQueue()}
function schedule(id,delay){if(id!==runId||disposed)return;clearRetry();retryTimer=setTimeout(()=>{retryTimer=null;if(id===runId&&!disposed)connect()},delay)}
function append(bytes){let remain=used-head;if(head>0&&buffer.length-used<bytes.length){if(remain)buffer.copyWithin(0,head,used);head=0;used=remain}if(buffer.length-used<bytes.length){let capacity=buffer.length;while(capacity-used<bytes.length)capacity*=2;const next=new Uint8Array(capacity);if(used>head)next.set(buffer.subarray(head,used));used=remain;head=0;buffer=next}buffer.set(bytes,used);used+=bytes.length}
function u16(p){return buffer[p]|(buffer[p+1]<<8)}
function u32(p){return (buffer[p]|(buffer[p+1]<<8)|(buffer[p+2]<<16)|(buffer[p+3]<<24))>>>0}
function recordError(message,force){if(!resyncing||force){errors++;consecutiveErrors++;state(message,'bad');updateDebug()}resyncing=true;return consecutiveErrors>=5}
function updateDebug(){if(debug)debugEl.textContent='Sequence: '+lastSequence+' · Resolution: '+resolution+' · Decoded: '+decoded+' · Dropped: '+dropped+' · Protocol errors: '+errors}
function decode(payload,n){let s=0,d=0;while(s<payload.length&&d<n){const control=payload[s++],length=(control&127)+1;if(control&128){if(s>=payload.length||d+length>n)return false;rawPixels.fill(payload[s++],d,d+length);d+=length}else{if(s+length>payload.length||d+length>n)return false;rawPixels.set(payload.subarray(s,s+length),d);s+=length;d+=length}}return d===n&&s===payload.length}
function compactQueue(){if(head===used){head=0;used=0}else if(head>buffer.length/2){const remain=used-head;buffer.copyWithin(0,head,used);head=0;used=remain}}
function parse(){while(used-head>=4){if(buffer[head]!==82||buffer[head+1]!==70||buffer[head+2]!==83||buffer[head+3]!==49){let found=-1;for(let i=head+1;i+3<used;i++){if(buffer[i]===82&&buffer[i+1]===70&&buffer[i+2]===83&&buffer[i+3]===49){found=i;break}}if(found<0){const discarded=Math.max(0,used-head-3);if(discarded&&recordError('收到的视频数据格式异常，正在重新同步。'))return false;head=used-3;break}if(found>head&&recordError('收到的视频数据格式异常，正在重新同步。'))return false;head=found;continue}
if(used-head<20)break;const w=u16(head+6),h=u16(head+8),length=u32(head+10),pixels=w*h,maxPayload=pixels+Math.ceil(pixels/128)+16;if(buffer[head+4]!==3||!w||!h||w>MAX_WIDTH||h>MAX_HEIGHT||pixels>MAX_FRAME_PIXELS||length<1||length>maxPayload){head++;if(recordError('收到的视频数据格式异常，正在重新同步。',true))return false;continue}if(used-head<20+length)break;const sequence=u32(head+14),ok=decode(buffer.subarray(head+20,head+20+length),pixels);head+=20+length;if(!ok){dropped++;if(recordError('视频帧解码异常，已丢弃这一帧。',true))return false;continue}consecutiveErrors=0;resyncing=false;lastSequence=String(sequence);resolution=w+'×'+h;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;rgba=new Uint8ClampedArray(pixels*4);imageData=new ImageData(rgba,w,h)}for(let i=0,j=0;i<pixels;i++,j+=4){const v=rawPixels[i];rgba[j]=((v>>5)&7)*255/7;rgba[j+1]=((v>>2)&7)*255/7;rgba[j+2]=(v&3)*255/3;rgba[j+3]=255}ctx.putImageData(imageData,0,0);decoded++;document.getElementById('bytes').textContent=length+' B';connectionInfo.textContent='Host: '+location.hostname+' · Mode: Raw · Resolution: '+resolution+((w!==320||h!==240)?' · Warning: unexpected resolution':'');state('视频流已连接','ok');updateDebug()}
compactQueue();return true}
function occupiedMessage(){return '当前已有其他 Viewer 正在使用视频流。\n请关闭其他浏览器标签页、Windows 兼容工具 CameraStreamViewer.exe 或其他视频软件，然后点击“重新连接”。'}
function networkMessage(){return '视频流连接失败。请确认：\n1. 当前 Wi-Fi 是 esp32s3cam-xxxx；\n2. ESP32 没有刚刚重启；\n3. 浏览器可以访问 http://192.168.4.1/。'}
async function rawLoop(id){activeKind='raw';const requestController=new AbortController();controller=requestController;try{const response=await fetch('http://'+location.hostname+':81/raw',{cache:'no-store',signal:requestController.signal});if(id!==runId){if(response.body)response.body.cancel().catch(()=>{});return}if(response.status===503){if(response.body)response.body.cancel().catch(()=>{});state(occupiedMessage(),'bad');schedule(id,5000);return}if(!response.ok)throw new Error('HTTP '+response.status);if(!response.body||!response.body.getReader){state('当前浏览器不支持 Raw 流，已切换到 MJPEG 兼容模式。','bad');mode='mjpeg';updateMode();schedule(id,1500);return}state('视频流已连接，正在接收画面……','ok');const streamReader=response.body.getReader();reader=streamReader;while(id===runId){const part=await streamReader.read();if(part.done)break;append(part.value);if(!parse())throw new Error('protocol')}if(id===runId)throw new Error('stream ended')}catch(error){if(id!==runId||error.name==='AbortError')return;if(reader){reader.cancel().catch(()=>{});reader=null}requestController.abort();if(error.message==='protocol'){state('收到的视频数据持续异常，已暂停并正在重新连接。','bad');schedule(id,1500)}else{state(networkMessage(),'bad');schedule(id,1500)}}finally{if(controller===requestController)controller=null;if(reader)reader=null}}
async function probeOccupied(id){const probe=new AbortController();controller=probe;try{const response=await fetch('/metrics',{cache:'no-store',signal:probe.signal});if(!response.ok)return false;const m=await response.json();return id===runId&&!!m.stream_active}catch(_){return false}finally{if(controller===probe)controller=null}}
async function mjpegLoop(id){activeKind='mjpeg';canvas.hidden=true;img.hidden=false;connectionInfo.textContent='Host: '+location.hostname+' · Mode: MJPEG · Resolution: 等待视频帧';state('正在连接 MJPEG 兼容流……');const probe=new AbortController();controller=probe;let metrics=null;try{const response=await fetch('/metrics',{cache:'no-store',signal:probe.signal});if(response.ok)metrics=await response.json()}catch(_){}finally{if(controller===probe)controller=null}if(id!==runId)return;if(metrics&&metrics.stream_active){state(occupiedMessage(),'bad');schedule(id,5000);return}
const outcome=await new Promise(resolve=>{let settled=false;const finish=value=>{if(settled)return;settled=true;if(mjpegResolve===finish)mjpegResolve=null;resolve(value)};mjpegResolve=finish;img.onload=()=>{if(id===runId){state('视频流已连接（MJPEG）','ok');connectionInfo.textContent='Host: '+location.hostname+' · Mode: MJPEG · Resolution: 由摄像头流提供'}};img.onerror=()=>finish('error');img.src='http://'+location.hostname+':81/stream?nocache='+Date.now()});if(id!==runId||outcome==='stopped')return;if(outcome==='error'){if(await probeOccupied(id)){state(occupiedMessage(),'bad');schedule(id,5000)}else{state(networkMessage(),'bad');schedule(id,1500)}}}
function connect(){if(disposed)return;const previousDone=activeDone,previousKind=activeKind;runId++;const id=runId;clearRetry();stopActive();activeKind=mode;canvas.hidden=mode!=='raw';img.hidden=mode!=='mjpeg';connectionInfo.textContent='Host: '+location.hostname+' · Mode: '+(mode==='raw'?'Raw':'MJPEG')+' · Resolution: '+(mode==='raw'?'320×240':'等待视频帧');state(mode==='raw'?'正在连接视频流……':'正在连接 MJPEG 兼容流……');activeDone=(async()=>{await previousDone.catch(()=>{});if(id!==runId||disposed)return;if(previousKind==='mjpeg')await new Promise(resolve=>setTimeout(resolve,200));if(id!==runId||disposed)return;if(mode==='raw')await rawLoop(id);else await mjpegLoop(id)})()}
function updateMode(){modeBtn.textContent=mode==='raw'?'切换到 MJPEG 兼容模式':'切换到 Raw 低延迟模式'}
document.getElementById('reconnect').onclick=()=>connect();modeBtn.onclick=()=>{mode=mode==='raw'?'mjpeg':'raw';updateMode();connect()};
async function pollMetrics(){if(disposed)return;if(metricsInFlight)return;metricsInFlight=true;const request=new AbortController();metricsController=request;try{const response=await fetch('/metrics',{cache:'no-store',signal:request.signal});if(!response.ok)throw new Error('metrics HTTP '+response.status);const m=await response.json();document.getElementById('fps').textContent=(m.fps??'--')+' fps';document.getElementById('pfps').textContent=(m.processing_fps??'--')+' fps';document.getElementById('ptime').textContent=(m.last_processing_ms??'--')+' ms';document.getElementById('bytes').textContent=(m.last_frame_bytes??'--')+' B';document.getElementById('heap').textContent=(m.free_heap??'--')+' B';document.getElementById('psram').textContent=(m.free_psram??'--')+' B';metricsStatus.textContent='Metrics 已更新'}catch(_){if(!disposed)metricsStatus.textContent='Metrics 暂不可用；视频流会继续独立运行'}finally{if(metricsController===request)metricsController=null;metricsInFlight=false;if(!disposed)metricsTimer=setTimeout(pollMetrics,1000)}}
function dispose(){if(disposed)return;disposed=true;runId++;clearRetry();if(metricsTimer!==null){clearTimeout(metricsTimer);metricsTimer=null}if(metricsController){metricsController.abort();metricsController=null}stopActive()}
window.addEventListener('pagehide',dispose,{once:true});updateMode();pollMetrics();connect();
})();
</script></body></html>)HTML";
